using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Ling.Interceptors.ExternalGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ExternalCallerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output => output.AddSource("ExternalCaller.g.cs", SourceText.From("""
            // <auto-generated/>
            internal static class ExternalCaller
            {
                internal static void Invoke(Service service) => service.Run("generated");
            }
            """, Encoding.UTF8)));
    }
}
